#!/usr/bin/env python3
"""Refuses to commit anything that looks like a real person's application.

This repository is public and holds no candidates. The `.gitignore` keeps the
configured locations out, but it cannot help with a CV saved somewhere new, a
real address pasted into a test, or a real filename quoted in a changelog —
and all three have happened.

Two checks, both mechanical:

  * a document outside the example set, which is what a stray CV looks like;
  * an email address that is not a reserved placeholder.

Neither can tell a real person's *name* from an invented one. That part is a
rule in AGENTS.md, and this hook is the floor under it rather than a
replacement for it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# A CV arrives as one of these. `.txt` and `.md` are deliberately absent: they
# are most of this repository.
DOCUMENT_SUFFIXES = (".pdf", ".doc", ".docx", ".odt", ".rtf")

# The one place documents belong: invented people, generated by a script that
# is itself reviewable. docs/example-cvs.md says so.
DOCUMENTS_ALLOWED_IN = ("example/cvs/",)

ADDRESS = re.compile(r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b")

# RFC 2606 reserves .test, .example and .invalid, and example.com/net/org, for
# exactly this. Everything else here is a placeholder this repository already
# documents.
PLACEHOLDER = re.compile(
    r"@([A-Za-z0-9.-]*\.)?(test|example|invalid|localhost)$"
    r"|@example\.(com|net|org)$"
    r"|@(acme|your-project|your-domain|their-domain|example)\."
    r"|@[A-Za-z0-9.-]*\.iam\.gserviceaccount\.com$"
    r"|@users\.noreply\.github\.com$"
    r"|@company\.",
    re.I,
)

# Binary files are read for the document check only; there is no point
# scanning them for addresses.
TEXT_SUFFIXES = (".py", ".md", ".toml", ".yaml", ".yml", ".txt", ".cfg", ".ini", ".sh", ".json")


def document_hits(paths: list[Path]) -> list[str]:
    """Documents staged outside the example set."""
    return [
        f"{path}: a {path.suffix} outside {DOCUMENTS_ALLOWED_IN[0]} is what a stray CV looks like. "
        "Candidate data never lands in this repository."
        for path in paths
        if path.suffix.lower() in DOCUMENT_SUFFIXES
        and not any(str(path).startswith(allowed) for allowed in DOCUMENTS_ALLOWED_IN)
    ]


def address_hits(paths: list[Path]) -> list[str]:
    """Addresses that are not reserved placeholders."""
    found = []
    for path in paths:
        if path.suffix.lower() not in TEXT_SUFFIXES or not path.exists():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for line_number, line in enumerate(text.splitlines(), start=1):
            for address in ADDRESS.findall(line):
                if PLACEHOLDER.search(address):
                    continue
                found.append(
                    f"{path}:{line_number}: {address} is not a reserved placeholder. "
                    "Use an @example.com or .test address; a real one may belong to a real applicant."
                )
    return found


def main(argv: list[str]) -> int:
    paths = [Path(a) for a in argv]
    problems = document_hits(paths) + address_hits(paths)
    if not problems:
        return 0
    print("Refusing this commit — it may carry a real person's data:\n", file=sys.stderr)
    for problem in problems:
        print(f"  {problem}", file=sys.stderr)
    print(
        "\nIf one of these is genuinely an invented example, give it a reserved name "
        "(.test, or example.com) or put the document in example/cvs/.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
